//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket_Food
    {
        public int Food_Id { get; set; }
        public Nullable<int> Enterprise_Id { get; set; }
        public Nullable<int> Food_Quantity { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Food_Photo { get; set; }
        public string Ingredient { get; set; }
    }
}
