//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise_Comments
    {
        public int Comment_Id { get; set; }
        public int Order_Id { get; set; }
        public string Comment { get; set; }
        public string Score { get; set; }
        public string Date_of_Comment { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
