//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise_Type
    {
        public int Enterprise_Id { get; set; }
        public string Enterprise_Type1 { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
