//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Type
    {
        public int Order_No { get; set; }
        public Nullable<int> Order_Type_Id { get; set; }
        public string Order_Type1 { get; set; }
    }
}
