//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Enterprise_Comments = new HashSet<Enterprise_Comments>();
            this.Orderline = new HashSet<Orderline>();
        }
    
        public int Order_Id { get; set; }
        public int Enterprise_Id { get; set; }
        public int Customer_Id { get; set; }
        public string Order_Date { get; set; }
        public string Order_Note { get; set; }
        public int Payment_Type_Id { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public string Order_Time { get; set; }
        public string Arrival_Time { get; set; }
        public string Total_Price { get; set; }
        public Nullable<int> Situation_Id { get; set; }
        public Nullable<int> Comment_State_Id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Comment_State Comment_State { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enterprise_Comments> Enterprise_Comments { get; set; }
        public virtual Order_State Order_State { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderline> Orderline { get; set; }
    }
}
