//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morder
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_of_Restaurant
    {
        public string User_Id { get; set; }
        public Nullable<int> Enterprise_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
        public string User_Phone_Number { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
